name: .NET Format
on:
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - run: dotnet restore KOTORModSync.sln /p:TargetFramework=net9.0
    - run: dotnet format whitespace --verify-no-changes KOTORModSync.sln --verbosity diagnostic